; Default language and accent options
; https://gtts.readthedocs.io/en/latest/module.html#localized-accents
[TTS]
default_language = en
default_top_level_domain = co.uk
languages = "de", "en", "es", "fr", "it", "pl", "pt", "ru", "zh-CN", "zh-TW"
tlds = "com", "com.au", "com.br", "com.mx", "co.in", "co.uk", "co.za"

[audio]
target_samplerate = 48000
input_device = CABLE Input (VB-Audio Virtual Cable)
output_device = Headphones audio-technica (Realtek(R) Audio)
device_suffix = , Windows WASAPI

[window]
window_height = 220
window_width = 400
is_resizeable = False
always_on_top = True